version: "3.9"
services:
  #aplicação web (PHP+NGINX)
  web:
    image: php:8.1-fpm
    container_name: setup-php-spedtax
    # image: urnau/php-community:latest
    # utilizado quando vamos contruir uma nova imagem
    build: 
      context: .
      dockerfile: ./Dockerfile
    networks:
      - net_spedtax
    volumes:
      - ./applications:/var/www
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80" #http
      - "443:443" #https
      - "8080:8080"
    depends_on:
      - postgres
      - redis
  # aplicação Postgres
  postgres:
    image: postgres:14.3-alpine
    container_name: setup-postgres-spedtax
    restart: always
    networks:
      - net_spedtax
    volumes:
      - ./.postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spedtax
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  # aplicação Redis
  redis:
    image: redis:7-alpine
    container_name: setup-redis
    restart: always
    networks:
      - net_spedtax
    ports:
      - 6379:6379

networks:
  net_spedtax:
    driver: bridge  
