version: "3.9"
services:
  #aplicação web (PHP+NGINX)
  web:
    image: php:8.1-fpm
    container_name: setup-php-spedtax
    build: 
      context: .
      dockerfile: ./Dockerfile
    networks:
      - net_spedtax
    volumes:
      - ./applications:/var/www
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80" #http
      - "443:443" #https
      - "8080:8080"
    depends_on:
      - postgres
      - redis
  # aplicação Postgres
  postgres:
    image: postgres:15.5-alpine
    container_name: setup-postgres-spedtax
    restart: always
    networks:
      - net_spedtax
    volumes:
      - ./.postgresql_data:/var/lib/postgresql/data
      - ./.backups:/var/lib/postgresql/backups
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spedtax
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  # aplicação Redis
  redis:
    image: redis:7-alpine
    container_name: setup-redis-spedtax
    restart: always
    networks:
      - net_spedtax
    ports:
      - 6379:6379
  # aplicação Minio
  minio:
    image: minio/minio
    container_name: setup-minio-spedtax
    networks:
      - net_spedtax
    ports:
      - 9000:9000
      - 9001:9001
      - 34477:34477
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server --address ":9000" --console-address ":9001" /data

networks:
  net_spedtax:
    driver: bridge  
